### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by lachyc** [lachyc/cheatsheet#18]

**Comment by lewibee** [comment]
![13323952_1039159582799044_2038390338_o](https://cloud.githubusercontent.com/assets/19521192/15761203/34ab0c64-2917-11e6-9217-7a6e1d4d4734.jpg)

**Comment by lewibee** [comment]
![logo](https://cloud.githubusercontent.com/assets/19521192/15904908/129f2344-2db3-11e6-81a2-7edf3989ee0e.png)
